### ISSUE TITLE
Slow to load database view when query lengths are substantional

### ISSUE THREAD

**Issue by Mayzie** [powa-team/powa-web#160]
Hi there!

When trying to browse into a database and at a time when there has been a large query (length of a query string like 7,000,000 characters), basically the entire view takes ages to load (and load it does after some length of time) with the view just being a loading spinner. When it loads, hovering over the long queries causes it to try to display the entire query.

I don't really know how else to expand on this. Basically, long query string length = very slow and unusable PoWA web.

I think the best course of action in such a case is to truncate the query before sending it to the web application (`substring(pg_stat_statements.query, ...)`), and to return the length of the query as well (`octet_length(pg_stat_statements.query)` and/or `length(pg_stat_statements.query)`), and display as such in the user interface.

Yeah I know I shouldn't have such long queries, it was a mistake on my part. But it revealed a flaw. 🙂

**Comment by rjuju** [comment]
Hi,

Thanks a lot for the report!  That's certainly not something we've beeing testing, so I can imagine that it can lead to unexpected problems in various places of the code.

I will try to reproduce it locally, but in the mean time one thing you could do is open the "developer tools" on your browser (usually available with F12), go to the network tab and refresh one of the slow page.  You should then be able to see all calls from the browser to the powa-web app, and see if (and how much) the slowness comes from the backend part.

**Comment by rjuju** [comment]
Thanks!  Well, that's very surprising as this endpoint shouldn't access the query text at all.

Which version of powa-web are you using?  I know there were some inefficiencies in some of the SQL statements in previous version, but the last one is https://github.com/powa-team/powa-web/commit/d3e6137f91d21176f406922bf3bc5c76c13c9f4c, which was fixed in version 4.1.0.

**Comment by Mayzie** [comment]
It's a local database. 

I disabled `pg_wait_sampling` (by removing it from `shared_preload_libraries` and restarting Postgres), but powa-web still stalls on that endpoint, although this time I get a nice big red banner at the top stating:

```
<local>: powa_take_snapshot(0): function "powa_wait_sampling_snapshot) failed: pg_wait_sampling shared memory wasn't initialized yet
```

**Comment by Mayzie** [comment]
> UPDATE powa_functions SET enabled = false WHERE module = 'pg_wait_sampling' AND srvid = 0;

Ran the above.

>Once done you can refresh the page and it won't execute that endpoint. If everything is fast, we will know where to focus.

Yup, everything is fast again! 🙂 Although, it still executes the endpoint (returns a JSON array of 3 elements, each being a ClientWrite and shows them under the "Wait events for all queries" section of the interface) - unsure if this is still expected?

**Comment by rjuju** [comment]
Ah right, for local servers we don't use the powa catalog to filter things in the UI, as we have a cheap and direct access to the real information.  Instead it's necessary to drop the extension on the powa database.  This will call an event trigger which will do the necessary cleanup in the powa_functions table.  Creating the extension again will call another event trigger which will reenable the extension in powa_functions table.

So, what this means is that there wasn't a lot of activity on that database in the last hour, which is why the endpoint is fast, and doesn't return a lot of data.  If you change the time interval to about 16 hours ago, it should be slow again.

If that's the case, and assuming you have more than 24h data retention, we can try to diagnose the slowdown.  Is there any chance you can do some partial dump of the powa tables?  I would only need powa_statements, powa_databases, powa_wait_sampling_history and powa_wait_sampling_history_current I think.  On those, the only one that can contain sensitive information is powa_databases (if you care about your database names), and powa_statements obviously.  I don't need those information anyway, so you could restore those data in a new database, replace the content with any random data and dump it again and it should still be enough to reproduce the problem locally.

If that's too problematic, I can help you to do the analysis on your database by providing various statements to find the source of the problem, but it will require quite a lot of back and forth.
