### ISSUE TITLE
cannot find powa-web 4

### ISSUE THREAD

**Issue by laurentjoly** [powa-team/powa-web#88]
Hi,

I would like to install powa 4, but I cannot find th tar.gz file, the following command doesn't find anything:

wget https://pypi.io/packages/source/p/powa-web/powa-web-4.0.0.tar.gz

**Comment by rjuju** [comment]
Hello,

Unfortunately powa4 is still in beta at the moment, that's why there's no such package available.  The only blocker for the release is one pull request (on powa-web), so I hope that we can release the v4 soon.

If you want to test the beta, you can still use the version from the git repository or the docker images

**Comment by laurentjoly** [comment]
Thanks for the answer. I am trying the beta version
